In [1]:
import numpy as np
import matplotlib.pyplot as plt

raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X) 
y_train = np.array(raw_data_y)

x = np.array([8.09,3.37])

In [2]:
%run ../MLPlus/Chap4_KNN/KNN.py # 加载那个py中的函数们

In [3]:
predict_y = kNN_classify(6,X_train,y_train,x) # 快乐运行封装好的函数
predict_y

1

## 使用scikit-learn中的KNN

导入-->创建实例-->传入参数，拟合数据集-->预测

In [4]:
from sklearn.neighbors import KNeighborsClassifier

In [5]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6) # 等同于自己实现的ｋ

In [6]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [7]:
X_predict = x.reshape(1,-1)

In [8]:
kNN_classifier.predict(X_predict) # 为了他家的接口统一，尽量写成矩阵扔进去

array([1])

## 重新整理自己的代码

注意可以写一些私有函数

此外，repr可以定义返回自己时该干的事情
```python
    def __repr__(self):
        return "KNN(k=%d)" % self.k
```

In [9]:
%run ../MLPlus/Chap4_KNN/KNN_STD.py

In [10]:
knn_clf=KNNClassifier(k=6)

In [11]:
knn_clf.fit(X_train,y_train)

KNN(k=6)

In [12]:
X_predict

array([[8.09, 3.37]])

In [13]:
y_predict = knn_clf.predict(X_predict)

In [14]:
y_predict

array([1])

In [17]:
knn_clf._predict(np.array([8.,3.])) # emmm 形同预设的私有

1