## Chap4.3判断机器学习算法的性能

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### tarin_test_split

不能直接进行分离，因为实际上是按照y的顺序排好的

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

假设取了前100个作为训练集，那么训练集中木有2，肯定爆炸

x，y实际上是分离的，所以不能直接随机的shuffle

方法1：结合然后shuffle

方法2：仅仅对于索引进行乱序处理

方法3：randomseed

In [9]:
shuffle_indexes = np.random.permutation(len(X)) # 生成长度为lenX的随机长度数组，作为索引

In [12]:
test_ratio = 0.2 # 测试集的比例
test_size = int(len(X)*test_ratio) # 强制类型转换防止索引爆炸

In [13]:
test_size

30

In [14]:
test_indexes = shuffle_indexes[:test_size] # 测试集
trian_indexes = shuffle_indexes[test_size:] # 训练集

In [29]:
X_train = X[trian_indexes]
X_test = X[test_indexes]

y_train = y[trian_indexes]
y_test = y[test_indexes]

randomseed方法测试

In [30]:
ytest1 = y.copy()
ytest2 = y.copy()

In [31]:
np.random.seed(666)
np.random.shuffle(ytest1)
ytest1

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 1, 2, 2, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 1, 1, 0, 1,
       0, 0, 2, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 2, 1, 2, 2, 2, 2, 0, 2, 2, 1, 1, 2, 2, 1, 2, 1,
       0, 2, 0, 1, 1, 2, 0, 2, 2, 0, 2, 2, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2,
       1, 2, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 2])

In [32]:
np.random.seed(666)
np.random.shuffle(ytest2)
ytest2

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 1, 2, 2, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 1, 1, 0, 1,
       0, 0, 2, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 2, 1, 2, 2, 2, 2, 0, 2, 2, 1, 1, 2, 2, 1, 2, 1,
       0, 2, 0, 1, 1, 2, 0, 2, 2, 0, 2, 2, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2,
       1, 2, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 2])

### 使用封装好的算法

In [35]:
from Chap4_KNN.model_selection import train_test_split

在同级目录下将打包好的包写好，并且扔一个__init__.py，则可以直接在文件中对这个“包”进行调用

In [45]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_ratio=0.2)

In [48]:
X_train.shape

(120, 4)

In [49]:
y_train.shape

(120,)

In [50]:
from Chap4_KNN.KNN_STD import KNNClassifier

In [51]:
my_knn_clf = KNNClassifier(k=3)

In [52]:
my_knn_clf.fit(X_train,y_train)

KNN(k=3)

In [53]:
y_predict = my_knn_clf.predict(X_test)

In [54]:
y_predict

array([1, 0, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 1,
       2, 1, 0, 0, 1, 2, 0, 2])

In [55]:
y_test

array([1, 0, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       2, 1, 0, 0, 1, 2, 0, 2])

In [56]:
sum(y_predict==y_test)

29

In [57]:
sum(y_predict==y_test)/len(y_test)

0.9666666666666667

### sklearn中的train_test_split

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2) # sklearn中叫的是test_size

In [61]:
X_train.shape

(120, 4)