## numpy.array中的运算

给定一个向量，每一个数变为原来的两倍

单纯的python自带的list版本

In [1]:
n = 10
L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

直接用乘法相当于扩充了两倍，如果希望是每一个元素都变为原来的两倍，则需要用下边的方法

In [3]:
A = []
for i in L:
    A.append(2*i)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
n = 1000000
L = [i for i in range(n)]

In [5]:
%%time
A = []
for i in L:
    A.append(2*i)

CPU times: user 94.9 ms, sys: 11.8 ms, total: 107 ms
Wall time: 105 ms


In [6]:
%%time
A = [2*i for i in L]

CPU times: user 37.6 ms, sys: 16.3 ms, total: 53.9 ms
Wall time: 53 ms


用列表生成表达式速度会比用迭代的快很多

下边尝试测试用numpy的

In [7]:
import numpy as np
L2 = np.arange(n)
L2

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [8]:
%%time
A=np.array([2*e for e in L2])

CPU times: user 344 ms, sys: 302 ms, total: 646 ms
Wall time: 240 ms


In [9]:
%%time
B = 2*L2

CPU times: user 3.34 ms, sys: 0 ns, total: 3.34 ms
Wall time: 1.99 ms


In [10]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [11]:
B

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

可以发现，直接用乘法，快的一批

In [12]:
n = 10
L = np.arange(n)
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Universal Function

思想即为将数组看成矩阵或者向量进行运算，近乎支持所有的加减乘除

In [13]:
X = np.arange(1,16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [15]:
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [17]:
X/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [18]:
X//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

两个斜杠代表整数的除法，结果进行向下取整

In [19]:
X**2 # 幂运算

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [20]:
X%2 #取余数

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [21]:
1/X #取倒数

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

### 一些特殊的运算

In [22]:
np.abs(X) # 绝对值

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
np.cos(X) # 余弦运算

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [24]:
np.exp(X) # e的指数

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [25]:
np.power(3,X) # 底数改为任意数字

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [26]:
3**X # 等价于上边的

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [27]:
np.log(X) # 取e为底的

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [28]:
np.log10(X) #取10为底的

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵间的运算

In [29]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [30]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [31]:
A+B

array([[10, 11],
       [12, 13]])

In [32]:
B2=[1,2]
A+B2

array([[1, 3],
       [3, 5]])

In [33]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [34]:
A*B # 乘法的话，不是矩阵相乘，而是单纯的对应元素相乘

array([[ 0, 10],
       [20, 30]])

#### numpy中，默认所有的运算符是针对于每一个元素来进行的

In [35]:
A/B

array([[0. , 0.1],
       [0.2, 0.3]])

In [36]:
A.dot(B) # 矩阵的乘法

array([[10, 10],
       [50, 50]])

In [37]:
Ａ

array([[0, 1],
       [2, 3]])

In [38]:
A.T # 矩阵的转置

array([[0, 2],
       [1, 3]])

### 向量和矩阵进行运算

In [39]:
v=np.array([1,2])
v

array([1, 2])

In [40]:
A

array([[0, 1],
       [2, 3]])

In [41]:
A + v

array([[1, 3],
       [3, 5]])

默认矩阵与向量进行加法，即矩阵的每一行都加了一下那个向量（等价于一个数字与之加，numpy）

In [42]:
np.vstack([v]*4) # 手动升维大法

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

另外一个 tile函数，可以指定每个维度都怎么堆叠升维

In [43]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [44]:
np.tile(v,(1,2))

array([[1, 2, 1, 2]])

In [45]:
v

array([1, 2])

In [46]:
A

array([[0, 1],
       [2, 3]])

In [47]:
v*A

array([[0, 2],
       [2, 6]])

In [48]:
v.dot(A)

array([4, 7])

In [49]:
A.dot(v) # numpy会自动把向量转方向，弄到可以运算，不过不建议这样

array([2, 8])

### 矩阵的逆

In [50]:
A

array([[0, 1],
       [2, 3]])

In [51]:
invA =  np.linalg.inv(A) # linalg线性代数lineralgebra的意思 invers逆的意思

In [52]:
A.dot(invA) # 矩阵的逆定义：与原矩阵相乘为单位阵，并且可以反过来

array([[1., 0.],
       [0., 1.]])

方阵才可能会有逆矩阵，且与之互为逆矩阵，数学中可以用伪逆矩阵，原矩阵与伪逆矩阵相乘也为单位阵

In [53]:
C = np.arange(16).reshape(2,8)

In [54]:
C

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [55]:
pinvC = np.linalg.pinv(C)
pinvC

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [56]:
C.dot(pinvC)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])

注：矩阵与伪逆矩阵相乘不一定为单位阵，偶尔为单位阵，其严格定义为XAX=A AXA=A

In [57]:
D = np.arange(8).reshape(2,4)
D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
pinvD = np.linalg.pinv(D)

In [59]:
D.dot(pinvD)

array([[ 1.00000000e+00,  2.28983499e-16],
       [-1.88737914e-15,  1.00000000e+00]])

In [60]:
pinvD.dot(D).dot(pinvD)

array([[-0.475,  0.175],
       [-0.2  ,  0.1  ],
       [ 0.075,  0.025],
       [ 0.35 , -0.05 ]])

In [61]:
pinvD

array([[-0.475,  0.175],
       [-0.2  ,  0.1  ],
       [ 0.075,  0.025],
       [ 0.35 , -0.05 ]])

In [62]:
D.dot(pinvD).dot(D)

array([[9.15933995e-16, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00],
       [4.00000000e+00, 5.00000000e+00, 6.00000000e+00, 7.00000000e+00]])

In [63]:
D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])