## Chap3.3-3.4 Numpy array基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.2'

## Python List 特点

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5] = 100

In [5]:
L[5]

100

In [6]:
L[6]='222'

In [7]:
L

[0, 1, 2, 3, 4, 100, '222', 7, 8, 9]

python中list十分灵活，可以存储多种类型，但是也造成了其效率低下
python中单一数据类型的列表可以用array

In [8]:
import array

In [9]:
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[2]

2

i 表示数据类型为整形

array保存效率较高的单一数据类型，也可以写二维数组
但是并没有将多维数组看成向量或者矩阵，提供相关的接口

## numpy.array

In [11]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

注意方括号，其代表列表生成式

In [12]:
nparr[5]

5

In [13]:
nparr[5]=100
nparr[5]

100

In [14]:
nparr.dtype

dtype('int64')

In [15]:
nparr[6] = 6.28
nparr[6]

6

numpy.array只能存储一种类型，用dtype进行查看，其他的类型能转的自动转化为整形

In [16]:
nparrf = np.array([1,2,3.0])

In [17]:
nparrf.dtype

dtype('float64')

初始化时加入float，则自动默认整个数组为float类型（C++与java里叫double）

## 其他创建numpy.array的方法

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(10).dtype

dtype('float64')

In [20]:
np.zeros(10,dtype=int).dtype

dtype('int64')

In [21]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

第一个参数为形状，第二个参数为数据类型，数据类型默认为浮点数

In [24]:
np.ones(shape=(3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
a = np.full(shape=(3,5),fill_value=666)

In [26]:
a
a.dtype

dtype('int64')

In [27]:
a

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

ones,zeros默认数据类型为浮点，fill默认类型看传入的参数

### arange

In [28]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

range第一个数字起始，第二个终止不包含，第三个为步长

In [30]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

arrange直接返回一个nparray，不用np.array()来转换了，另外是range不支持步长为浮点，而后者支持

### linspace(liner-space)

In [32]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

等间距在前闭后闭的区间内生成第三个参数的个数的值

In [33]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [34]:
np.random.randint(0,10)

2

In [35]:
np.random.randint(0,10,10)

array([1, 9, 3, 1, 8, 6, 5, 2, 7, 3])

前闭后开的区间内，第三个参数不为1则生成有第三个参数的个数的向量

In [36]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

第三个参数叫size，避免混淆可以注明此外那个可以入一个元组生成多维的

In [37]:
np.random.randint(0,1,(2,3))

array([[0, 0, 0],
       [0, 0, 0]])

random默认是靠随机种子变出来的，所以指定好随机种子可以让随机矩阵变成一个固定的矩阵

In [38]:
np.random.seed(666)

In [40]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [41]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6],
       [4, 7, 5, 5, 5]])

In [42]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

不过随机种子仿佛要每次都指定一下，不然每次会自动刷新,不过刷新的规律也是固定的

In [43]:
np.random.random()

0.2811684913927954

In [45]:
np.random.random((3,5))

array([[0.23340091, 0.76706421, 0.81995656, 0.39747625, 0.31644109],
       [0.15551206, 0.73460987, 0.73159555, 0.8578588 , 0.76741234],
       [0.95323137, 0.29097383, 0.84778197, 0.3497619 , 0.92389692]])

random.random默认生成（0,1）之间均匀分布的浮点数，normal生成正态分布

In [46]:
np.random.normal(0,1,(3,5))

array([[ 0.22196962, -1.86735182, -0.25584759, -1.76438083, -0.94249688],
       [-1.58045861,  0.90472662, -0.82628327,  0.82101369,  0.36712592],
       [ 1.65399586,  0.13946473, -1.21715355, -0.99494737, -1.56448586]])

三个参数分别为均值，标准差，矩阵形状

np.random.normal? 函数名/模块名+？可以快速查看文档，help（）可以让文档直接显示在笔记本内