## FancyIndexing

In [2]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
x[3]

3

In [4]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [5]:
x[3:9:2]

array([3, 5, 7])

如果希望可以访问特定索引的值，一种方法是一个个访问，另外一个方法就是把索引写成一个list,然后传入

In [6]:
ind = [3,5,8]

In [7]:
x[ind]

array([3, 5, 8])

In [8]:
ind = np.array([[0,2],[1,3]])
ind

array([[0, 2],
       [1, 3]])

In [9]:
x[ind] # 可以索引出来并且建立成索引形状的矩阵

array([[0, 2],
       [1, 3]])

In [10]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row = np.array([0,1,2])
col = np.array([0,1,2])
X[row,col]

array([ 0,  5, 10])

In [12]:
X[0,col] # 自动升维

array([0, 1, 2])

In [13]:
X[:2,col]

array([[0, 1, 2],
       [4, 5, 6]])

In [14]:
col = [True, False, True, True]

In [16]:
X[1:3,col] # 对于False的不要

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy中的比较

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [19]:
x>=3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [20]:
x ==3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
x!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [23]:
2*x == 24-4*x # 可以写复杂的表达式

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [24]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [26]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
np.sum(x <= 3) # 默认True=1

4

In [28]:
np.count_nonzero(x<=3) # 不为零的=1

4

In [29]:
np.any(x == 0) # 有一个使之成立，则返回True

True

In [30]:
np.any(x<0)

False

In [32]:
np.all(x>=0) # 所有的都成立才可以

True

In [34]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
np.sum(x%2==0) #计数偶数

8

In [38]:
np.sum(X%2==0,axis=1) # 看每一行有多少偶数

array([2, 2, 2, 2])

In [39]:
np.sum(X%2==0,axis=0)

array([4, 0, 4, 0])

In [40]:
np.all(X>0,axis=1)

array([False,  True,  True,  True])

### 组合方法

In [41]:
np.sum((x>3)&(x>10))

5

In [43]:
(x>3)&(x<10) # 相当于两个布尔型矩阵进行了与运算，而&&代表着两个布尔值的运算，二者不一样

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False])

In [46]:
np.sum((x%2==0)|(x>10))

11

In [47]:
np.sum(~(x==0)) # 对于向量同样的，需要用～代表非，而不能用！

15

In [50]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
x[x<5] # 根据刚才返回的布尔型列表选出值-->小于5的

array([0, 1, 2, 3, 4])

In [56]:
X%2==0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [59]:
X[X[:,3]%3==0,:] # 每一行的末尾是否可以被3整除，作为一个向量

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [65]:
X[X%2==0] # 而直接扔进去一个二维的矩阵，则会挑出来一堆东西,并且搞成一个向量

array([ 0,  2,  4,  6,  8, 10, 12, 14])

更加高级的函数，基本是用Pandas进行预处理，搞成numpy，可以看看Pandas