## 聚合操作-各种统计啥的

In [1]:
import numpy as np

L = np.random.random(100)

L

array([0.33996627, 0.06221318, 0.36644914, 0.48355264, 0.97962257,
       0.25751006, 0.83641701, 0.73357043, 0.59835442, 0.04402152,
       0.70849667, 0.82810951, 0.12510743, 0.97260778, 0.30491564,
       0.45960301, 0.59102275, 0.67641862, 0.4693188 , 0.93662419,
       0.89059253, 0.11630606, 0.08261019, 0.43785665, 0.78823096,
       0.25966158, 0.75990719, 0.84898865, 0.79997385, 0.48298246,
       0.50466639, 0.08143666, 0.616952  , 0.98486816, 0.69106487,
       0.0119978 , 0.7180185 , 0.64430724, 0.16573783, 0.02363167,
       0.44458924, 0.8142569 , 0.5674013 , 0.28494401, 0.85145957,
       0.88673506, 0.15180418, 0.36424809, 0.11435432, 0.68269044,
       0.4205545 , 0.76077904, 0.845662  , 0.91483149, 0.35768459,
       0.20524059, 0.59292431, 0.14837128, 0.78088347, 0.42867892,
       0.48215134, 0.85466663, 0.83697754, 0.48022188, 0.38181027,
       0.79897494, 0.07781973, 0.09181258, 0.1689134 , 0.5033228 ,
       0.22026435, 0.94566265, 0.31939298, 0.22100455, 0.02686

In [2]:
sum(L)

50.26854243615663

In [3]:
np.sum(L)

50.268542436156636

原生的肯定没有自己的好用

In [4]:
bigarray = np.random.random(100000)
%time sum(bigarray)
%time np.sum(bigarray)

CPU times: user 44.8 ms, sys: 32.6 ms, total: 77.3 ms
Wall time: 11.4 ms
CPU times: user 443 µs, sys: 328 µs, total: 771 µs
Wall time: 116 µs


49915.51013448428

In [5]:
np.min(L)

0.004693903741803673

In [6]:
np.max(L)

0.9848681619192463

注：可以使用面向对象的方法调用属性，效果相同

In [7]:
L.max()

0.9848681619192463

In [8]:
L.min()

0.004693903741803673

建议用np的方法，属性的那个日常不全

In [9]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.sum(X)

120

默认对于向量，矩阵都是可以的，同时，如果希望降维版本的聚合的话可以指定axis

In [11]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [12]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

axis代表沿着哪个方向进行运算，或者说，把哪个方向的轴压缩为1

In [13]:
np.prod(X) # 返回所有元素的乘积

0

In [14]:
np.prod(X+1) # python天然支持大数运算，不用特别担心整形溢出

20922789888000

In [15]:
np.mean(X) #平均值

7.5

In [16]:
np.median(X) # 中位数

7.5

In [17]:
np.percentile(bigarray, 50) # 第50%的元素

0.4987846524529394

In [18]:
for percent in [0,25,50,75,100]:
    print(np.percentile(bigarray,percent))

6.890646369273057e-06
0.24968859859115491
0.4987846524529394
0.7483953203603991
0.9999886203148346


In [19]:
np.percentile(bigarray,[0,25,50,75,100])

array([6.89064637e-06, 2.49688599e-01, 4.98784652e-01, 7.48395320e-01,
       9.99988620e-01])

In [20]:
np.var(bigarray)# 方差

0.08307797187399386

In [21]:
np.std(bigarray) # 标准差

0.28823249621441693

In [22]:
x = np.random.normal(0,1,size=1000000) # 均值为0， 标准差为1的正态分布

In [23]:
np.mean(x)

-0.0006484368442771315

In [24]:
np.std(x)

1.0006574286588357

## 索引

In [25]:
np.min(x)

-5.17261161968342

In [26]:
np.argmin(x) # 返回最小值的位置索引

795942

In [27]:
x[489775]

0.3210805349365084

In [28]:
np.argmax(x)

521878

## 排序与索引

In [29]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
np.random.shuffle(x) # 乱序处理，并且自主改x
x

array([15,  3, 13,  0, 11,  4,  6, 14,  5,  1, 10, 12,  7,  8,  9,  2])

In [31]:
np.sort(x)# 排序.返回一个正序的。不对x进行操作

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
x

array([15,  3, 13,  0, 11,  4,  6, 14,  5,  1, 10, 12,  7,  8,  9,  2])

In [33]:
x.sort() # 找x接着或者用这个方法
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
X = np.random.randint(16,size=(4,4))
X

array([[ 6, 11, 11,  1],
       [ 1, 12,  3,  0],
       [ 6,  3,  7,  4],
       [15, 10,  6, 15]])

In [35]:
np.sort(X)

array([[ 1,  6, 11, 11],
       [ 0,  1,  3, 12],
       [ 3,  4,  6,  7],
       [ 6, 10, 15, 15]])

可以看到，如果没有指定的话，是对每一行进行排序

In [36]:
np.sort(X,axis=1) # 默认值为1，沿着列方向进行排序，被压为1的那个轴最后变得整齐

array([[ 1,  6, 11, 11],
       [ 0,  1,  3, 12],
       [ 3,  4,  6,  7],
       [ 6, 10, 15, 15]])

In [37]:
np.sort(X,axis=0) # 沿着行排序，每一列被和谐

array([[ 1,  3,  3,  0],
       [ 6, 10,  6,  1],
       [ 6, 11,  7,  4],
       [15, 12, 11, 15]])

In [38]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
np.random.shuffle(x)
x

array([ 8,  3, 10, 14,  9,  1,  5,  4, 11,  2, 12,  6,  0,  7, 13, 15])

In [40]:
np.argsort(x) # 返回了每一个值的应该的顺序的索引

array([12,  5,  9,  1,  7,  6, 11, 13,  0,  4,  2,  8, 10, 14,  3, 15])

In [41]:
np.partition(x,3) # 按照3为标定点进行一次快排中的操作，左比3小右比3大

array([ 1,  0,  2,  3,  4,  6,  5,  7,  8, 11, 12,  9, 14, 10, 13, 15])

In [42]:
np.argpartition(x,3) # 返回上边那个数的索引版本

array([ 5, 12,  9,  1,  7, 11,  6, 13,  0,  8, 10,  4,  3,  2, 14, 15])

In [43]:
X

array([[ 6, 11, 11,  1],
       [ 1, 12,  3,  0],
       [ 6,  3,  7,  4],
       [15, 10,  6, 15]])

In [44]:
np.argsort(X,axis=1) # 矩阵同理

array([[3, 0, 1, 2],
       [3, 0, 2, 1],
       [1, 3, 0, 2],
       [2, 1, 0, 3]])

In [45]:
np.argpartition(X,3,axis=1) # 注：标定点需要是存在的数字

array([[3, 0, 2, 1],
       [3, 0, 2, 1],
       [1, 3, 0, 2],
       [2, 1, 0, 3]])